# -*- coding: utf-8 -*-
"""CSV-Softset_converter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cn_g6IquHfA0RBH1OxZEa0kZWWBDgJi-

#Deneme

U ve E kümeleri herhangi bir csv dosyasından alınıp cebirsel olarak soft set haline dönüştürülüyor. U kümesinin elemanları u_i ler E kümesinin elemanları e_i ler olarak düşünüldü.
"""

import pandas as pd
from io import StringIO
from textwrap import dedent

# *** SADECE GOOGLE COLAB ORTAMINDA DOSYA YÜKLEME İÇİN GEREKLİ KOD ***
try:
    from google.colab import files
except ImportError:
    # Colab dışındaysa dosyaları simüle edilmiş içerikten alır
    files = None

def soft_set_olusturucu(csv_data):
    """
    Yüklenen CSV verisinden Soft Set (F, A) yapısını hesaplar.
    """
    # 1. Veriyi Oku ve Matrise Dönüştür
    try:
        # dedent ile gereksiz boşlukları temizle ve StringIO ile pandas'a aktar
        df = pd.read_csv(StringIO(dedent(csv_data)), index_col=0)
    except Exception as e:
        return f"Hata: CSV dosyası okunurken sorun oluştu: {e}"

    # 2. Eşleştirme Sözlüklerini Oluştur
    firma_ids = df.index.tolist()
    urun_ids = df.columns.tolist()

    U_eslestirme = {fid: f'u_{i+1}' for i, fid in enumerate(firma_ids)}
    A_eslestirme = {uid: f'e_{i+1}' for i, uid in enumerate(urun_ids)}

    # 3. Soft Set'in Yaklaşık Fonksiyonunu (Phi) Hesapla
    soft_set_phi = {}
    for urun_id in urun_ids:
        urun_etiketi = A_eslestirme[urun_id]
        sutun_verisi = df[urun_id]

        # Değeri 0'dan büyük olan Firmaların (u_k) etiketlerini topla
        # Hata ihtimaline karşı veriyi sayıya dönüştürürken hata yoksayılır.
        alt_kume = [
            U_eslestirme[fid]
            for fid, deger in sutun_verisi.items()
            if pd.to_numeric(deger, errors='coerce') > 0
        ]

        soft_set_phi[urun_etiketi] = "{" + ", ".join(alt_kume) + "}"

    # 4. Sonuçları Formatla (Hata ihtimali olan satırlar temizlendi)
    U_tanim = ', '.join([f'{v}: {k}' for k, v in U_eslestirme.items()])
    A_tanim = ', '.join([f'{v}: {k}' for k, v in A_eslestirme.items()])

    output = "### 📝 Soft Set Cebirsel Tanımı\n"
    output += f"* **Evrensel Küme (Adaylar):** **U** = $u_i$ (Firma ID'ler)\n"
    output += f"> **Eşleştirme:** {U_tanim}\n\n"
    output += f"* **Parametre Kümesi (Öznitelikler):** **A** = $e_i$ (Ürün ID'ler)\n"
    output += f"> **Eşleştirme:** {A_tanim}\n\n"

    # Hata veren 53. satırın düzeltilmiş ve temizlenmiş hali:
    output += f"* **Soft Set $\\mathbf{{(F, A)}}$: Yaklaşık Fonksiyon $\\mathbf{{\\Phi}}(e_i)$ Kümeleri**\n"

    for e, alt_kume in soft_set_phi.items():
        output += f"  * $\\mathbf{{\\Phi}}({e})$: {alt_kume}\n"

    return output

# --- ANA ÇALIŞTIRMA BLOĞU ---

if files:
    # Colab ortamında dosya yükleme arayüzünü açar
    print("Lütfen CSV dosyanızı yükleyin (Colab penceresi açılacaktır):")
    yuklenen_dosyalar = files.upload()

    if yuklenen_dosyalar:
        dosya_adi = list(yuklenen_dosyalar.keys())[0]
        # Yüklenen dosyadan içeriği oku
        csv_icerigi = yuklenen_dosyalar[dosya_adi].decode('utf-8')

        soft_set_cebirsel_tanim = soft_set_olusturucu(csv_icerigi)
        print("\n--- Analiz Sonuçları ---\n")
        print(soft_set_cebirsel_tanim)
    else:
        print("Dosya yüklenmedi. Lütfen tekrar deneyin.")

else:
    # Eğer Colab ortamı değilse (örneğin bu arayüz), manuel içerik kullanılır
    print("\n--- Yüklü Dosya İçeriği ile Çalıştırma ---")
    manuel_csv_icerigi = """
FirmaID,52757,88109,3350,64670,120333,105628,61375,24349,117567,118605,107321,113309,73320,3347,40640,17226,78845,93712,3190,119476
6567,0,0,0,0,0,0,9800,0,0,0,0,0,0,0,0,0,0,0,0,0
5871,0,24700,0,0,0,24590,1600,0,4260,0,0,2170,0,0,0,0,2850,0,0,0
4775,0,0,3400,17450,0,0,0,0,6250,0,0,0,0,0,0,0,0,0,370150,0
8179,13900,0,0,0,0,0,0,26850,0,0,2000,1000,0,0,0,0,0,0,0,0
974,0,1100,0,4500,0,0,0,0,0,0,1500,0,0,0,0,0,0,3645,0,2907
713,0,0,0,0,0,0,0,0,0,0,1375,0,0,0,0,0,0,0,0,0
3797,28500,0,0,0,0,0,0,0,0,0,1000,1200,0,0,0,0,1200,18500,0,500
5096,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5815,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
897,100903,0,0,0,55000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2027,0,23570,0,500,0,0,0,4900,1200,0,0,0,0,0,0,0,0,0,17465,0
3008,0,0,16000,0,0,0,0,0,0,1900,0,0,0,0,0,0,0,0,0,0
872,0,0,0,0,0,0,1200,0,0,5950,0,0,0,0,1300,0,0,0,0,0
9975,5500,0,0,0,0,1500,0,0,0,600,0,0,0,0,0,0,0,0,0,0
2537,0,0,0,4800,0,0,0,75425,0,0,0,0,0,0,0,0,0,0,0,0
2842,4000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,19550,0,0
5336,0,0,0,0,0,0,112750,0,0,0,0,0,0,0,0,0,4100,0,0,0
6885,0,1600,6000,0,0,0,443279,0,0,0,0,0,0,0,0,0,0,0,0,0
9206,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6372,0,7450,0,0,0,0,0,5500,0,0,0,0,0,6100,0,0,0,0,1000,0
"""
    soft_set_cebirsel_tanim = soft_set_olusturucu(manuel_csv_icerigi)
    print(soft_set_cebirsel_tanim)

"""U_i ler sadece sayılarla gösterildi."""

import pandas as pd
from io import StringIO
from textwrap import dedent

# *** SADECE GOOGLE COLAB ORTAMINDA DOSYA YÜKLEME İÇİN GEREKLİ KOD ***
try:
    from google.colab import files
except ImportError:
    files = None

def soft_set_olusturucu_guncel(csv_data):
    """
    Yüklenen CSV verisinden Soft Set (F, A) yapısını hesaplar.
    Firma ID'lerini doğrudan 1, 2, 3... olarak etiketler.
    """
    # 1. Veriyi Oku ve Matrise Dönüştür
    try:
        df = pd.read_csv(StringIO(dedent(csv_data)), index_col=0)
    except Exception as e:
        return f"Hata: CSV dosyası okunurken sorun oluştu: {e}"

    # 2. Eşleştirme Sözlüklerini Oluştur
    firma_ids = df.index.tolist()
    urun_ids = df.columns.tolist()

    # YENİ EŞLEŞTİRME: Firma ID'leri (U) sadece sıra numarası (1, 2, 3...) olacak.
    U_eslestirme = {fid: str(i + 1) for i, fid in enumerate(firma_ids)}
    A_eslestirme = {uid: f'e_{i+1}' for i, uid in enumerate(urun_ids)}

    # 3. Soft Set'in Yaklaşık Fonksiyonunu (Phi) Hesapla
    soft_set_phi = {}
    for urun_id in urun_ids:
        urun_etiketi = A_eslestirme[urun_id]
        sutun_verisi = df[urun_id]

        # Değeri 0'dan büyük olan Firmaların (1, 2, 3...) etiketlerini topla
        alt_kume = [
            U_eslestirme[fid]
            for fid, deger in sutun_verisi.items()
            if pd.to_numeric(deger, errors='coerce') > 0
        ]

        soft_set_phi[urun_etiketi] = "{" + ", ".join(alt_kume) + "}"

    # 4. Sonuçları Formatla
    U_tanim = ', '.join([f'{v}: {k}' for k, v in U_eslestirme.items()])
    A_tanim = ', '.join([f'{v}: {k}' for k, v in A_eslestirme.items()])

    output = "### 📝 Soft Set Cebirsel Tanımı (Güncellenmiş Firma Adları)\n"
    output += f"* **Evrensel Küme (Adaylar):** **U** = $1, 2, \\dots, 20$ (Firma ID'ler)\n"
    output += f"> **Eşleştirme:** {U_tanim}\n\n"
    output += f"* **Parametre Kümesi (Öznitelikler):** **A** = $e_i$ (Ürün ID'ler)\n"
    output += f"> **Eşleştirme:** {A_tanim}\n\n"

    output += f"* **Soft Set $\\mathbf{{(F, A)}}$: Yaklaşık Fonksiyon $\\mathbf{{\\Phi}}(e_i)$ Kümeleri**\n"

    for e, alt_kume in soft_set_phi.items():
        output += f"  * $\\mathbf{{\\Phi}}({e})$: {alt_kume}\n"

    return output

# --- ANA ÇALIŞTIRMA BLOĞU ---
# (Colab'de çalıştırıldığında dosya yükleme arayüzünü açar)

if files:
    print("Lütfen CSV dosyanızı yükleyin (Colab penceresi açılacaktır):")
    yuklenen_dosyalar = files.upload()

    if yuklenen_dosyalar:
        dosya_adi = list(yuklenen_dosyalar.keys())[0]
        csv_icerigi = yuklenen_dosyalar[dosya_adi].decode('utf-8')

        soft_set_cebirsel_tanim = soft_set_olusturucu_guncel(csv_icerigi)
        print("\n--- Analiz Sonuçları (Güncel Firma Adları) ---\n")
        print(soft_set_cebirsel_tanim)
    else:
        print("Dosya yüklenmedi. Lütfen tekrar deneyin.")

else:
    soft_set_cebirsel_tanim = soft_set_olusturucu_guncel(manuel_csv_icerigi)
    print(soft_set_cebirsel_tanim)

"""#2 RMVC entegrasyonu

Bu halini kopyalayıp yapıştırıp RMVC içine gömebilir miyim?

"""

