# -*- coding: utf-8 -*-
"""CSVtoRMVC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QCjgjG8y6050LfUdh_cECvbyYTgpFa9t

#1 RMVC entegrasyonu



Bir .csv dosyasını yükleyip RMVC değerleri hesaplanır mı?
"""

# =============================================================================
# RMVC ANALİZ RAPORU - GOOGLE COLAB VERSİYONU
# =============================================================================
# Bu kodu Google Colab hücresine yapıştırıp çalıştırın (Play ikonu).
# Ardından "Dosya Seç" butonu belirecektir, CSV dosyanızı oradan yükleyin.
# =============================================================================

from google.colab import files
import io
import pandas as pd
from fractions import Fraction

# ==========================================
# 1. VERİ OKUMA VE DÖNÜŞTÜRME (MAPPING)
# ==========================================

def load_and_map_csv_content(csv_content):
    """
    CSV içeriğini (string) okur, Ürünleri (1,2,3..) ve Firmaları (e_1,e_2..) olarak kodlar.
    """
    try:
        E_named = {}          # { 'e_1': {'1', '3'}, ... }
        firm_mapping = {}     # { 'e_1': 'GerçekFirmaID' }
        product_mapping = {}  # { '1': 'GerçekÜrünID' }
        U = set()             # Evrensel küme (1, 2, 3...)

        # Dosya içeriğini satırlara böl
        lines = csv_content.splitlines()

        # --- 1. Başlık Satırı (Ürün İsimlerini Kodla) ---
        header_line = lines[0].strip()
        headers = header_line.split(',')

        real_product_ids = [pid.strip() for pid in headers[1:]] # İlk sütun hariç

        # Ürünleri 1'den başlayarak numaralandır
        real_to_simple_prod = {}
        for idx, real_pid in enumerate(real_product_ids):
            simple_id = str(idx + 1) # "1", "2", "3"...
            product_mapping[simple_id] = real_pid
            real_to_simple_prod[real_pid] = simple_id

        U = set(product_mapping.keys())

        # --- 2. Veri Satırlarını İşle (Firmaları Kodla) ---
        valid_rows = 0
        for index, line in enumerate(lines[1:]):
            line = line.strip()
            if not line: continue

            parts = line.split(',')
            real_firma_id = parts[0].strip()
            quantities = parts[1:]

            bought_products_simple = set()

            # Miktarları kontrol et
            for i, qty in enumerate(quantities):
                try:
                    if i < len(real_product_ids) and float(qty) > 0:
                        real_pid = real_product_ids[i]
                        simple_pid = real_to_simple_prod[real_pid]
                        bought_products_simple.add(simple_pid)
                except ValueError:
                    continue

            # Firma kod adı atama (e_1, e_2...)
            code_name = f"e_{valid_rows+1}"

            E_named[code_name] = bought_products_simple
            firm_mapping[code_name] = real_firma_id
            valid_rows += 1

        print(f"\n[BİLGİ] Veri yüklendi. {len(U)} ürün ve {len(E_named)} firma işlendi.")
        return U, E_named, firm_mapping, product_mapping

    except Exception as e:
        print(f"[HATA] Veri işlenirken sorun oluştu: {e}")
        return None, None, None, None

# ==========================================
# 2. GÖRSELLEŞTİRME: SOFT SET TANIMI
# ==========================================

def print_soft_set_definition(U, E_named):
    sorted_u = sorted(list(U), key=lambda x: int(x))
    sorted_e = sorted(E_named.keys(), key=lambda x: int(x.split('_')[1]))

    print("\n" + "="*100)
    print(f"{'SOFT SET DEFINITION (MATEMATİKSEL TANIM)':^100}")
    print("="*100)

    u_str = ", ".join(sorted_u)
    print(f"U (Universal Set) = {{{u_str}}}")
    print("-" * 100)

    e_str = ", ".join(sorted_e)
    print(f"E (Parameters)    = {{{e_str}}}")
    print("-" * 100)

    print("Mappings (Φ):")
    for e_key in sorted_e:
        elements = sorted(list(E_named[e_key]), key=lambda x: int(x))
        elements_str = ", ".join(elements) if elements else "∅"
        print(f"  Φ({e_key}) = {{{elements_str}}}")
    print("="*100)
    print("\n")

# ==========================================
# 3. GÖRSELLEŞTİRME: BINARY MATRIX
# ==========================================

def print_binary_matrix(E_named, prod_map):
    sorted_product_keys = sorted(prod_map.keys(), key=lambda x: int(x))
    sorted_firms = sorted(E_named.keys(), key=lambda x: int(x.split('_')[1]))
    col_width = 8

    print("="*100)
    print(f"{'INITIAL BINARY MATRIX (1=Var, 0=Yok)':^100}")
    print("="*100)

    header_str = f"{'SETS':<12}"
    for pid in sorted_product_keys:
        header_str += f"{pid:>{col_width}}"
    print(header_str)
    print("-" * len(header_str))

    for e_key in sorted_firms:
        row_str = f"{e_key:<12}"
        current_set = E_named[e_key]
        for pid in sorted_product_keys:
            val = "1" if pid in current_set else "0"
            row_str += f"{val:>{col_width}}"
        print(row_str)

    print("-" * len(header_str))
    print("\n")

# ==========================================
# 4. RMVC HESAPLAMA MOTORU
# ==========================================

def delta_function(e_name, E_named, U):
    e_set = E_named[e_name]
    not_in_e_set = U - e_set
    results = {}
    all_sets_list = list(E_named.values())

    for element in not_in_e_set:
        total_sum = 0
        for other_element in e_set:
            pair = {element, other_element}
            count = sum(1 for s in all_sets_list if pair.issubset(s))
            total_sum += count
        results[element] = total_sum
    return results

def create_membership_matrix(E_keys, E_named, U):
    membership_matrix = {e_key: {} for e_key in E_keys}
    total_sets = len(E_named)

    print("[İŞLEM] RMVC Matrisi hesaplanıyor, lütfen bekleyin...")

    for e_key in E_keys:
        delta_results = delta_function(e_key, E_named, U)
        current_set_len = len(E_named[e_key])
        g_coeff = current_set_len * (total_sets - 1) if total_sets > 1 else 1

        for element in U:
            if element in delta_results:
                val = Fraction(delta_results[element], g_coeff) if g_coeff != 0 else 0
            else:
                val = 1
            membership_matrix[e_key][element] = val

    return membership_matrix

# ==========================================
# 5. SONUÇ RAPORLAMA
# ==========================================

def print_full_report(matrix, firm_map, prod_map):
    sorted_product_keys = sorted(prod_map.keys(), key=lambda x: int(x))
    sorted_firms = sorted(matrix.keys(), key=lambda x: int(x.split('_')[1]))
    col_width = 10

    print("="*110)
    print(f"{'MEMBERSHIP VALUE MATRIX (BAĞIL ÜYELİK MATRİSİ)':^110}")
    print("="*110)

    header_str = f"{'SETS':<12}"
    for pid in sorted_product_keys:
        header_str += f"{pid:>{col_width}}"
    print(header_str)
    print("-" * len(header_str))

    column_sums = {pid: 0.0 for pid in sorted_product_keys}

    for e_key in sorted_firms:
        row_str = f"{e_key:<12}"
        for pid in sorted_product_keys:
            val = float(matrix[e_key][pid])
            column_sums[pid] += val
            row_str += f"{val:>{col_width}.4f}"
        print(row_str)

    print("-" * len(header_str))

    sum_str = f"{'SUM s(x)':<12}"
    for pid in sorted_product_keys:
        sum_str += f"{column_sums[pid]:>{col_width}.4f}"
    print(sum_str)
    print("="*110)
    print("\n")

    # KARAR AŞAMASI
    print("="*75)
    print(f"{'DECISION MAKING PHASE (KARAR AŞAMASI)':^75}")
    print("="*75)

    sorted_scores = sorted(column_sums.items(), key=lambda x: x[1], reverse=True)

    print(f"{'Rank':<6} | {'Prod ID':<10} | {'Score s(x)':<15} | {'Original Product ID'}")
    print("-" * 75)

    for rank, (pid, score) in enumerate(sorted_scores, 1):
        prefix = "★ " if rank == 1 else "  "
        real_name = prod_map[pid]
        print(f"{prefix}{rank:<4} | {pid:<10} | {score:<15.4f} | {real_name}")

    print("-" * 75)
    winner_simple = sorted_scores[0][0]
    winner_real = prod_map[winner_simple]
    winner_score = sorted_scores[0][1]
    print(f"\n>>> FINAL DECISION: Optimal Product is '{winner_simple}' (Orig: {winner_real})")
    print(f">>> Highest Score: {winner_score:.4f}")
    print("="*75)
    print("\n")

    # REFERANS TABLOLARI
    print("#" * 30)
    print(f"{'REFERENCE TABLES':^30}")
    print("#" * 30)

    print("\n--- [1] FIRM ID MAPPING ---")
    print(f"{'Code':<10} | {'Original Firm ID'}")
    print("-" * 35)
    for code in sorted_firms:
        print(f"{code:<10} | {firm_map[code]}")

    print("\n--- [2] PRODUCT ID MAPPING ---")
    print(f"{'New ID':<10} | {'Original Product ID'}")
    print("-" * 35)
    for pid in sorted_product_keys:
        print(f"{pid:<10} | {prod_map[pid]}")

# ==========================================
# 6. COLAB ÇALIŞTIRMA BLOĞU
# ==========================================

print("Lütfen analiz edilecek CSV dosyasını yükleyin:")
uploaded = files.upload()

for fn in uploaded.keys():
    print(f'\nDosya alındı: "{fn}"')

    # Dosya içeriğini decode et (UTF-8)
    content = uploaded[fn].decode('utf-8-sig')

    # Analizi başlat
    U, E_named, firm_map, prod_map = load_and_map_csv_content(content)

    if U and E_named:
        print_soft_set_definition(U, E_named)
        print_binary_matrix(E_named, prod_map)
        membership_matrix = create_membership_matrix(E_named.keys(), E_named, U)
        print_full_report(membership_matrix, firm_map, prod_map)
    else:
        print("İşlem başarısız.")